import type { PRDData } from "./types"

export function generateMarkdown(data: PRDData, locale: "zh" | "en"): string {
  const isZh = locale === "zh"

  return `# ${isZh ? "产品需求文档 (PRD)" : "Product Requirements Document (PRD)"}

## ${isZh ? "产品一句话" : "Product One-liner"}
${data.oneliner}

## ${isZh ? "目标用户与场景" : "Target Users & Scenarios"}
${data.users}

## ${isZh ? "核心价值" : "Core Value"}
${data.value}

## ${isZh ? "关键路径" : "Key Path"}
${data.keypath}

## ${isZh ? "最小功能清单" : "Minimum Feature List"}
${data.features}

## ${isZh ? "非目标与暂不做" : "Non-goals & Not Doing"}
${data.nongoals}

## ${isZh ? "成功标准" : "Success Criteria"}
${data.success}

## ${isZh ? "依赖与约束" : "Dependencies & Constraints"}
${data.dependencies}

## ${isZh ? "风险与预案" : "Risks & Contingencies"}
${data.risks}

---
${isZh ? "由 Idea炼金术 生成" : "Generated by Idea Alchemy"} | ${new Date().toLocaleDateString()}
`
}

export function downloadMarkdown(data: PRDData, locale: "zh" | "en") {
  const markdown = generateMarkdown(data, locale)
  const blob = new Blob([markdown], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `prd-${Date.now()}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportToPDF() {
  window.print()
}
